import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { Inter } from "next/font/google";
import { TimerContextProvider } from "@/context/TimerContext";
import { TaskContextProvider } from "@/context/TaskContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pomodoro App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <TimerContextProvider>
          <TaskContextProvider>{children}</TaskContextProvider>
        </TimerContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
